### ISSUE TITLE
Content

### ISSUE THREAD

**Issue by serge-nikitin** [jscraft-org/jscraft.org#86]
Members can track what they read / watch / listen to about programming:
- articles
- books
- video couses
- video on youtube
- podcast

It's interesting for me to see what other professionals read / watch / listen to.

Also it can be possible to discuss in our discussions. 

Content table: 
- id
- create_at
- type (article | video | podcast | book)
- user_id
- title
- comment

But how to name it? Learning content? Not so good...

**Comment by odv** [comment]
Few suggestions: **Development resources**,  **Programming resources** or **Curated Programming Resources**
If I were to pick just one from what I've recommended above, I would go with **Curated Programming Resources** because it indicates that you are selective and you pay attention to the resources that you list.
